
const NotificationsActions = {
  INGEST_NOTIFICATION          : 'INGEST_NOTIFICATION',
  INGEST_NOTIFICATIONS         : 'INGEST_NOTIFICATIONS',
  REMOVE_ACCOUNT_NOTIFICATIONS : 'REMOVE_ACCOUNT_NOTIFICATIONS',
  MARK_NOTIFICATION_AS_READ    : 'MARK_NOTIFICATION_AS_READ'
};

export default NotificationsActions;