
const NotificationsActions = {
  INGEST_NOTIFICATION          : 'INGEST_NOTIFICATION',
  INGEST_NOTIFICATIONS         : 'INGEST_NOTIFICATIONS',
  REMOVE_ACCOUNT_NOTIFICATIONS : 'REMOVE_ACCOUNT_NOTIFICATIONS'
};

export default NotificationsActions;