
const SettingsActions = {
  SET_SETTINGS_VALUE                    : 'SET_SETTINGS_VALUE',
  SET_SOUND_SETTINGS_ENABLED            : 'SET_SOUND_SETTINGS_ENABLED',
  SET_NOTIFICATIONS_DOUBLE_CLICK_ACTION : 'SET_NOTIFICATIONS_DOUBLE_CLICK_ACTION'
};

export default SettingsActions;