
const SettingsActions = {
  SET_SETTINGS_VALUE                               : 'SET_SETTINGS_VALUE',
  SET_SOUND_SETTINGS_ENABLED                       : 'SET_SOUND_SETTINGS_ENABLED',
  SET_NOTIFICATIONS_DOUBLE_CLICK_ACTION            : 'SET_NOTIFICATIONS_DOUBLE_CLICK_ACTION',
  SET_CONFIRM_BEFORE_MARKING_NOTIFICATIONS_AS_READ : 'SET_CONFIRM_BEFORE_MARKING_NOTIFICATIONS_AS_READ'
};

export default SettingsActions;