
const SetupActions = {
  SET_SETUP_IS_LOADING   : 'SET_SETUP_IS_LOADING',
  SET_SETUP_SHOW_LOADING : 'SET_SETUP_SHOW_LOADING',
  SET_SETUP_RENDER_APP   : 'SET_SETUP_RENDER_APP',
  SET_WINDOW_FOCUSSED    : 'SET_WINDOW_FOCUSSED'
};

export default SetupActions;