
const SetupActions = {
  SET_SETUP_IS_LOADING    : 'SET_SETUP_IS_LOADING',
  SET_SETUP_SHOW_LOADING  : 'SET_SETUP_SHOW_LOADING',
  SET_SETUP_RENDER_APP    : 'SET_SETUP_RENDER_APP',
  SET_WINDOW_FOCUSSED     : 'SET_WINDOW_FOCUSSED',
  SET_ALT_KEY_DOWN        : 'SET_ALT_KEY_DOWN',
  SET_WINDOW_FULLSCREENED : 'SET_WINDOW_FULLSCREENED'
};

export default SetupActions;