
const SetupActions = {
  SET_SETUP_IS_LOADING    : 'SET_SETUP_IS_LOADING',
  SET_SETUP_SHOW_LOADING  : 'SET_SETUP_SHOW_LOADING',
  SET_SETUP_RENDER_APP    : 'SET_SETUP_RENDER_APP'
}

export default SetupActions;